add network access check for installation

diff --git a/vpnkit b/vpnkit
--- a/vpnkit
+++ b/vpnkit
@@ -39,6 +39,10 @@ wsl_need_restart=false
 # On Ubuntu Distrib, default user has uid=1000,gid=1000
 wsl_uid=1000
 wsl_gid=1000
+
+# shellcheck disable=1090
+[ -f "$wsl_init_distro_name" ] && . $wsl_init_distro_name
+
 #------------------------------------------------------------------------------
 
 help () {
@@ -58,6 +62,7 @@ help () {
 version () { echo "v$version" ; }
 step (){ echo -e "\033[0;32m== $1 ==\033[0m"; }
 info (){ echo -e "\033[1;33m=> $1\033[0m"; }
+err (){ echo -e "\033[1;31m=> $1\033[0m"; }
 need_root () { [ "$EUID" -eq 0 ] || { echo "Please restart with sudo";  exit $?; } ;}
 win_mkdirs () { mkdir -p "$(dirname "$docker_desktop_installer_exe")" "$(dirname "$vpnkit_shell")" ;}
 
@@ -73,7 +78,7 @@ do_dns_info () {
     tmp_file="$(mktemp)"
     $powershell -Command "Get-DnsClientServerAddress -AddressFamily IPv4 | \
                 Select-Object -ExpandProperty ServerAddresses" > "$tmp_file"
-        # Remove duplicates
+    # Remove duplicates
     /usr/bin/awk '!x[$0]++' "$tmp_file" > "$tmp_file".2
     IFS=$'\r\n' GLOBIGNORE='*' command eval  'nameservers=($(cat $tmp_file.2))'
     rm -f "$tmp_file" "$tmp_file".2
@@ -539,16 +544,22 @@ do_clean_all () {
 # Install parts on WSL
 
 do_install_prerequisites () {
+
     [ -z "$WSL_DISTRO_NAME" ] && {
-        echo "ERROR: $(basename "$0") WSL_DISTRO_NAME env variable missing "
+        err "ERROR: $(basename "$0") WSL_DISTRO_NAME env variable missing "
+        exit 1
+    }
+    curl -s -q http://www.google.com || {
+        err "ERROR: $(basename "$0") installation need network access"
+        err "Please verify your /etc/resolv.conf file..."
         exit 1
     }
     [ -f "$npiperelay_exe" ] && [ -f "$vpnkit_tap_vsockd_bin" ] && [ -f "$vpnkit_exe" ] || {
-        echo "ERROR: $(basename "$0") need dependencies. You should call it first with option --download"
+        err "ERROR: $(basename "$0") need dependencies. You should call it first with option --download"
         exit 1
     }
     [ -f "$vpnkit_config" ] && [ -f "$vpnkit_shell" ] && [ -f "$vpnkit_service" ] && [ -f "$vpnkit_resolv_conf" ] || {
-        echo "ERROR: $(basename "$0") has to be configured first with option --reconfigure"
+        err "ERROR: $(basename "$0") has to be configured first with option --reconfigure"
         exit 1
     }
 }
@@ -566,11 +577,15 @@ do_install_dependencies () {
 }
 
 do_install_init_distro_name () {
-    # WSL Dynamic Service Environement variables
-    [ -f $wsl_init_distro_name ] && \
-        info "Update $wsl_init_distro_name" || \
-        info "Create $wsl_init_distro_name"
-    echo "WSL_DISTRO_NAME=$WSL_DISTRO_NAME" > $wsl_init_distro_name
+    [ -z "$WSL_DISTRO_NAME" ] \
+        && err "WSL_DISTRO_NAME not set. Could not fill $wsl_init_distro_name (set it manually)" \
+    || {
+        # WSL Dynamic Service Environement variables
+        [ -f $wsl_init_distro_name ] && \
+            info "Update $wsl_init_distro_name" || \
+            info "Create $wsl_init_distro_name"
+        echo "WSL_DISTRO_NAME=$WSL_DISTRO_NAME" > $wsl_init_distro_name
+    }
 }
 
 do_install_wslkit_sudoers () {
@@ -735,8 +750,6 @@ do_status_all () {
 #------------------------------------------------------------------------------
 action=${1:-help}
 
-do_reconfigure_vpnkit_service
-exit
 case "$action" in
     -c|--clean) do_clean ;;
     -C|--clean-all) do_clean_all ;;
